commonLabels:
  app: "emailservice"
  env: "dev"
images:
- name: "docker.io/nginxdemos/hello"
  newTag: "0.3"
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namePrefix: "dev-"
patches:
- patch: "- op: replace\n  path: /spec/replicas\n  value: 1\n"
  target:
    kind: "Deployment"
    name: "emailservice"
resources:
- "../../base"
