apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-paymentservice-envs
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: dev
          - env: prod
            namespace: prod
  template:
    metadata:
      name: my-paymentservice-{{env}}
      labels:
        harness.io/serviceRef: my-paymentservice
        harness.io/envRef: {{env}}
    spec:
      project: default
      source:
        repoURL: https://github.com/crizstian/my-gitops-demo.git
        targetRevision: main
        path: apps/my-microservice/overlays/{{env}}
      destination:
        server: https://kubernetes.default.svc
        namespace: {{namespace}}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
